# Generated by Django 5.2.7 on 2025-10-20 03:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("groupchat", "0002_polloption_vote"),
        ("movies", "0004_alter_movie_movieid"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="polloption",
            name="group",
        ),
        migrations.AddField(
            model_name="polloption",
            name="votes",
            field=models.ManyToManyField(
                blank=True,
                related_name="voted_poll_options",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="polloption",
            name="movie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="poll_options",
                to="movies.movie",
            ),
        ),
        migrations.CreateModel(
            name="Poll",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polls",
                        to="groupchat.group",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="polloption",
            name="poll",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="options",
                to="groupchat.poll",
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Vote",
        ),
    ]
