# Generated by Django 5.2.7 on 2025-10-20 04:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("groupchat", "0003_remove_polloption_group_polloption_votes_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="poll",
            old_name="question",
            new_name="title",
        ),
    ]
