# Generated by Django 5.2.7 on 2025-10-18 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1000, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Keyword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1000, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProductionCompany",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=2000, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProductionCountry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=2000, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="SpokenLanguage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1000, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tmdb_id", models.BigIntegerField(unique=True)),
                ("movieId", models.TextField(blank=True, null=True)),
                ("title", models.CharField(max_length=5000)),
                (
                    "original_title",
                    models.CharField(blank=True, max_length=5000, null=True),
                ),
                ("overview", models.TextField(blank=True, null=True)),
                ("tagline", models.CharField(blank=True, max_length=5000, null=True)),
                ("status", models.CharField(blank=True, max_length=500, null=True)),
                ("release_date", models.DateField(blank=True, null=True)),
                ("runtime", models.IntegerField(blank=True, null=True)),
                ("revenue", models.BigIntegerField(blank=True, null=True)),
                ("budget", models.BigIntegerField(blank=True, null=True)),
                ("adult", models.BooleanField(default=False)),
                ("vote_average", models.FloatField(blank=True, null=True)),
                ("vote_count", models.IntegerField(blank=True, null=True)),
                ("popularity", models.FloatField(blank=True, null=True)),
                ("imdb_id", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "original_language",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("poster_path", models.URLField(blank=True, null=True)),
                ("backdrop_path", models.URLField(blank=True, null=True)),
                ("homepage", models.URLField(blank=True, null=True)),
                (
                    "genres",
                    models.ManyToManyField(related_name="movies", to="movies.genre"),
                ),
                (
                    "keywords",
                    models.ManyToManyField(related_name="movies", to="movies.keyword"),
                ),
                (
                    "production_companies",
                    models.ManyToManyField(
                        related_name="movies", to="movies.productioncompany"
                    ),
                ),
                (
                    "production_countries",
                    models.ManyToManyField(
                        related_name="movies", to="movies.productioncountry"
                    ),
                ),
                (
                    "spoken_languages",
                    models.ManyToManyField(
                        related_name="movies", to="movies.spokenlanguage"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Rating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=50)),
                ("rating", models.FloatField()),
                ("timestamp", models.DateTimeField(blank=True, null=True)),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="movies.movie",
                    ),
                ),
            ],
        ),
    ]
