# Generated by Django 5.2.7 on 2025-10-19 04:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0003_alter_rating_timestamp_comments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="movieId",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
